<package format="3">

  <name>robot_3d3s</name>
  <version>1.0.0</version>
  <description>URDF description package for 3-wheeled-driving 3-wheeled-steering (3d3s) omnidirectional robot</description>
  <author email="bushanovy@gmail.com">Yersaiyn Bushanovy</author>
  <maintainer email="bushanovy@gmail.com">Yersaiyn Bushanovy</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>gz_msgs_vendor</build_depend>
  <build_depend>gz_sim_vendor</build_depend>
  <build_depend>gz_transport_vendor</build_depend>

  <exec_depend>std_msgs</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf2_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_bt_navigator</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_planner</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_interfaces</exec_depend>
  <exec_depend>gz_msgs_vendor</exec_depend>
  <exec_depend>gz_sim_vendor</exec_depend>
  <exec_depend>gz_transport_vendor</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_ros gazebo_model_path="${prefix}/.."/>
  </export>
  
</package>
